rm(list=ls())
library(survival)
library(glmnet)
set.seed(7)
rd = read.csv('/nfs/nobackup/gerstung/awj/projects/ProbCox/compute/data/I8000_P1600.csv')
print(dim(rd))
ptm <- proc.time()
m <- glmnet(as.matrix(rd[, 4:dim(rd)[2]]), Surv(rd$V1, rd$V2, rd$V3), family ="cox")
print(proc.time() - ptm)

