rm(list=ls())
library(survival)
library(glmnet)
set.seed(7)
rd = read.csv('/nfs/nobackup/gerstung/awj/projects/ProbCox/compute/data/I8000_P1600.csv')
print(dim(rd))
ptm <- proc.time()
m = coxph(Surv(V1, V2, V3)~., data=rd)
print(proc.time() - ptm)
print(concordance(m))
